name: shader_theme_switcher
description: A Flutter package for creating beautiful, shader-driven theme transitions (shockwave effect).
version: 0.0.11
homepage: https://github.com/meeziest/shader_theme_switcher/tree/main?tab=readme-ov-file
repository: https://github.com/meeziest/shader_theme_switcher/tree/main?tab=readme-ov-file
issue_tracker: https://github.com/meeziest/shader_theme_switcher/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  shaders:
    - shaders/shockwave.frag
